# Generated by Django 3.0.6 on 2020-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleabout',
            name='active',
            field=models.BooleanField(verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='articleabout',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articleabout',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='articleabout',
            name='header',
            field=models.CharField(max_length=200, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='articleabout',
            name='picture',
            field=models.ImageField(upload_to='uploads/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='articleabout',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
