# Generated by Django 3.0.6 on 2020-06-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventphotomodel',
            options={'verbose_name': 'Событие :: Статья :: Фотография', 'verbose_name_plural': 'Событие :: Статья :: Фотографии'},
        ),
    ]
