# Generated by Django 3.0.6 on 2020-06-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200628_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='event_annotation',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='event_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='event_title',
            new_name='title',
        ),
    ]
