# Generated by Django 3.0.6 on 2020-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200628_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинал статьи'),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='source_link',
            field=models.CharField(blank=True, help_text='Ссылка указывается в формате http://www.address.com/some-page.html', max_length=255, verbose_name='URL-ссылка на оригинал статьи'),
        ),
    ]
