# Generated by Django 3.0.6 on 2020-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20200702_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphotomodel',
            name='alt',
            field=models.CharField(blank=True, help_text='Текст будет отображаться, если у пользователя выключены изображения. Также текст используется поисковыми системами для поиска изображений.', max_length=255, verbose_name='Описание изображения'),
        ),
    ]
