# Generated by Django 3.0.6 on 2020-07-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20200702_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация к статье'),
        ),
    ]
