# Generated by Django 3.0.6 on 2020-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_eventphotomodel_small_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='PhotoCarousel',
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер изображения 300 x 200', upload_to='images/events/%Y%m%d/', verbose_name='Файл изображения'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
